export const actions = {
    ON_BOARD: 'ON_BOARD',
    OFF_BOARD: 'OFF_BOARD',
    SHOW_LOADING: 'SHOW_LOADING',
    HIDE_LOADING: 'HIDE_LOADING',
    REQUEST_FAILED: 'REQUEST_FAILED',
    GET_APP_STATE: 'GET_APP_STATE',
    DISPLAY_FULL_SCREEN: 'DISPLAY_FULL_SCREEN',
    
    SET_ERROR_TOAST: 'SET_ERROR_TOAST',
    RESET_SUCCESS_TOAST: 'RESET_SUCCESS_TOAST',
    SET_SUCCESS_TOAST: 'SET_SUCCESS_TOAST',

    VALIDATE_MOBILE_USER_SUCCESS: 'VALIDATE_MOBILE_USER_SUCCESS'
}