export const actions = {
    GET_HOME_ASSESSMENTS: 'GET_HOME_ASSESSMENTS',
    CREATE_HOME_ASSESSMENT: 'CREATE_HOME_ASSESSMENT',
    GET_SINGLE_HOME_ASSESSMENT: 'GET_SINGLE_HOME_ASSESSMENT',
    GET_SINGLE_HOME_ASSESSMENT_STUDENTS: 'GET_SINGLE_HOME_ASSESSMENT_STUDENTS',
    GET_STUDENT_FEEDBACK: 'GET_STUDENT_FEEDBACK',
}