export const actions = {
    GET_CLASS_REGISTER: 'GET_CLASS_REGISTER',
    __GET_CLASS_REGISTER: '__GET_CLASS_REGISTER',
    GET_ATTENDANCE_REGISTER: 'GET_ATTENDANCE_REGISTER',
    CREATE_ATTENDANCE: 'CREATE_ATTENDANCE',
    UPDATE_ATTENDANCE: 'UPDATE_ATTENDANCE',
    OPEN_ATTENDANCE_REGISTER_REMOTELY: 'OPEN_ATTENDANCE_REGISTER_REMOTELY',
    OPEN_ATTENDANCE_REGISTER_LOCALLY: 'OPEN_ATTENDANCE_REGISTER_LOCALLY',
    UPDATE_UNSECHRONIZED_REGISTER: 'UPDATE_UNSECHRONIZED_REGISTER',
}