export const actions = {
    GET_ATTENDANCE_LIST: 'GET_ATTENDANCE_LIST',
    CREATE_ATTENDANCE: 'CREATE_ATTENDANCE',
    UPDATE_ATTENDANCE: 'UPDATE_ATTENDANCE',
    OPEN_ATTENDANCE_REGISTER: 'CREATE_ATTENDANCE',
}