export const actions = {
    GET_TUTOR_CLASSES: 'GET_TUTOR_CLASSES',
    GET_CLASS_SUBJECTS: 'GET_CLASS_SUBJECTS',
    GET_CLASS_GROUP: 'GET_CLASS_GROUP',
    GET_CLASS_STUDENTS: 'GET_CLASS_STUDENTS',
    GET_SESSION_CLASS_WITHOUT_SUBJ: 'GET_SESSION_CLASS_WITHOUT_SUBJ',
    GET_SESSION_CLASS_SUBJECT:'GET_SESSION_CLASS_SUBJECT',
}