export const actions = {
    GET_TUTOR_CLASSES: 'GET_TUTOR_CLASSES',
    GET_CLASS_SUBJECTS: 'GET_CLASS_SUBJECTS',
    GET_CLASS_GROUP: 'GET_CLASS_GROUP',
    GET_CLASS_STUDENTS: 'GET_CLASS_STUDENTS',
}