export const actions = {
    GET_CLASS_NOTES: 'GET_CLASS_NOTES',
    __GET_CLASS_NOTES: '__GET_CLASS_NOTES',
    GET_SHARED_CLASS_NOTES_CLASSES:'GET_SHARED_CLASS_NOTES_CLASSES',
    GET_OTHER_STAFF:'GET_OTHER_STAFF',
}