export const actions = {
    GET_CLASS_NOTES: 'GET_CLASS_NOTES',
    __GET_CLASS_NOTES: '__GET_CLASS_NOTES',
    UPDATE_CLASS_NOTE:'UPDATE_CLASS_NOTE',
    CREATE_CLASS_NOTE:'CREATE_CLASS_NOTE',
    SEND_FOR_APPROVAL:'SEND_FOR_APPROVAL',
}